repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: forbid-submodules
      - id: requirements-txt-fixer
        files: "requirements.*txt"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        exclude: "tests/.*"
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
      - id: autopep8
